SYNOPSIS
--------

#include <ubf.h>


int Bgetr (UBFH * p_ub, BFLDID *fldidocc, char * buf, BFLDLEN * buflen);
int Bgetrv (UBFH * p_ub, char * buf, BFLDLEN * buflen, ...);

Link with '-lubf -lnstd -lm -lpthread'

DESCRIPTION
-----------
Function is used lookup the the field in sub-UBF buffers. The exact field
from which to take the value at given sub-level, is specified in array of 
'fldidocc' or '...'. The array of value must consists in following form:

*<field_id_1>,<occurrence_1>,...,<field_id_N>,<occurrence_N>,BBADFLDOCC*.

Function uses *Bfind(3)* to search the sub-UBF buffer from internal UBF field IDs
and then value from the leaf UBF field ID / UBF buffer is extracted by *Bget(3)*.

Bgetr() function accepts array of BFLDID (int typed)  elements. Bgetrv() accepts
varargs filled with the same sequence of identifiers.

Usage:

Assuming that UBF buffer contains following data:

--------------------------------------------------------------------------------

T_STRING_8_FLD	HELLO WORLD1
T_STRING_9_FLD	01
T_STRING_9_FLD	20
T_STRING_9_FLD	31
T_CARRAY_2_FLD	
T_CARRAY_2_FLD	TEST CARRAY
T_PTR_3_FLD	0xc7
T_PTR_3_FLD	0x12b
T_UBF_FLD	
	T_SHORT_1_FLD	6500
	T_LONG_1_FLD	3200
T_UBF_FLD	
	T_LONG_3_FLD	9999
	T_LONG_3_FLD	8888
	T_UBF_3_FLD	
		T_STRING_9_FLD	HELLO WORLD ONE
		T_STRING_9_FLD  HELLO WORLD TWO
		T_STRING_9_FLD  HELLO WORLD THREE

--------------------------------------------------------------------------------

To extract *T_STRING_9_FLD* third occurrence value from *T_UBF_FLD/T_UBF_3_FLD* sub-buffer field,
use following syntax:

--------------------------------------------------------------------------------

ret=Bgetr(p_ub, (int []){ T_UBF_FLD,1,T_UBF_3_FLD,0,T_UBF_2_FLD,0,T_STRING_9_FLD,2,BBADFLDOCC}, buf, &len)

--------------------------------------------------------------------------------

or with var-args:

--------------------------------------------------------------------------------
ret=Bgetrv(p_ub, buf, &len, T_UBF_FLD,1,T_UBF_3_FLD,0,T_UBF_2_FLD,0,T_STRING_9_FLD,2,BBADFLDOCC)
--------------------------------------------------------------------------------


RETURN VALUE
------------
On success, *Bgetr()* and *Bgetrv()* return zero; on error, -1 is returned, with *Berror* set to 
indicate the error.

ERRORS
------
Note that *Bstrerror()* returns generic error message plus custom message with 
debug info from last function call. Function my return errors from *Bget(3)* and
from *Bfind(3)*. Following additional errors may be returned by this function:

*BALIGNERR* Corrupted buffer or pointing to not aligned memory area.

*BNOTFLD* Buffer not fielded, not correctly allocated or corrupted.

*BNOSPACE* No space in 'buf'.

*BBADFLD* Invalid field id passed.

*BNOTPRES* Field not present.

EXAMPLE
-------
See *ubftest/test_get.c* for sample code.

BUGS
----
Report bugs to support@mavimax.com

SEE ALSO
--------
*Bchg(3)* *Badd(3)* *CBadd(3)* *CBget(3)*

COPYING
-------
(C) Mavimax, Ltd

