SYNOPSIS
--------

#include <ubf.h>


int Bgetr (UBFH * p_ub, BFLDID *fldidocc, char * buf, BFLDLEN * buflen);
int Bgetrv (UBFH * p_ub, char * buf, BFLDLEN * buflen, ...);

Link with '-lubf -lnstd -lm -lpthread'

DESCRIPTION
-----------
Function is used lookup the the field in sub-UBF buffers. The exact field
from which to take the value at given sub-level, is specified in array of 
'fldidocc' or '...'. The array of value must consists in following form:

*<field_id_1>,<occurrence_1>,...,<field_id_N>,<occurrence_N>,BBADFLDOCC*.

Function uses *Bfind(3)* to search the sub-UBF buffer from internal UBF field IDs
and then value from the leaf UBF field ID / UBF buffer is extracted by *Bget(3)*.

Bgetr() function accepts array of BFLDID (int typed)  elements. Bgetrv() accepts
varargs filled with the same sequence of identifiers.

Usage:

Assuming that UBF buffer contains following data:

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

To extract that data from sub-buffer, calls would look like:

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

or

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------


RETURN VALUE
------------
On success, *Bgetr()* and *Bgetrv()* return zero; on error, -1 is returned, with *Berror* set to 
indicate the error.

ERRORS
------
Note that *Bstrerror()* returns generic error message plus custom message with 
debug info from last function call. Function my return errors from *Bget(3)* and
from *Bfind(3)*. Following additional errors may be returned by this function:

*BALIGNERR* Corrupted buffer or pointing to not aligned memory area.

*BNOTFLD* Buffer not fielded, not correctly allocated or corrupted.

*BNOSPACE* No space in 'buf'.

*BBADFLD* Invalid field id passed.

*BNOTPRES* Field not present.

EXAMPLE
-------
See *ubftest/test_get.c* for sample code.

BUGS
----
Report bugs to support@mavimax.com

SEE ALSO
--------
*Bchg(3)* *Badd(3)* *CBadd(3)* *CBget(3)*

COPYING
-------
(C) Mavimax, Ltd

