BNEXT(3)
========
:doctype: manpage


NAME
----
Bnext - Iterate over the UBF buffer


SYNOPSIS
--------

#include <ubf.h>

int Bnext (UBFH *'p_ub', BFLDID *'bfldid', BFLDOCC *'occ', char *'buf', BFLDLEN *'len');

Link with '-lubf -lnstd -lm -lpthread'

DESCRIPTION
-----------
Iterate over the UBF buffer pointed by 'p_ub'. To start (or restart) loop over the buffer, 
'bfldid' value must be set to *BFIRSTFLDID*. If function succeeds it returns field id in 
'bfldid', occurrence in 'occ' and data value in 'buf'/'len' pair. 'buf' and 'len' both are 
optional fields. 'len' on input indicate the buffer length, on output it indicates the the 
length of data loaded. If 'len' is set to NULL, then it is assumed that on input buffer is 
large enough to store data. The state of iteration is stored in thread local storage (TLS).

When Bnext steps onto *BFLD_VIEW* type field, it is expected that 'buf' points
to initialized BVIEWFLD field where 'data' field is set to pointer to area
where VIEW can be unloaded. To loop over the UBF buffer in generic way where
any type can be expected, it is advised that 'buf' before Bnext call is initialized
as BVIEWFLD. For example:

--------------------------------------------------------------------------------

char data_buf[1024];
BFLDID bfldid;
BFLDOCC occ;
BVIEWFLD *vf;
BFLDLEN  len;

/* prepare for view, for other types any data in buffer will be overwritten */
vf=(BVIEWFLD *)data_buf;
vf->data=data_buf+sizeof(BVIEWFLD);
len = sizeof(data_buf);

while(1==Bnext(p_ub, &bfldid, &occ, data_buf, &len))
{

    /* Process the retrieved data.. */

    /* prepare for view, for other types any data in buffer will be overwritten */
    vf=(BVIEWFLD *)data_buf;
    vf->data=data_buf+sizeof(BVIEWFLD);
    len = sizeof(data_buf);
}

--------------------------------------------------------------------------------

RETURN VALUE
------------
On success, *Bnext()* return *1*, if End Of Buffer reached, then *0* is returned; on error, 
-1 is returned, with *Berror* set to indicate the error.

ERRORS
------
Note that *Bstrerror()* returns generic error message plus custom message with debug info 
from last function call.

*BALIGNERR* Corrupted buffer or pointing to not aligned memory area.

*BNOTFLD* Buffer not fielded, not correctly allocated or corrupted.

*BNOSPACE* No space in 'buf'.

EXAMPLE
-------
See *ubftest/test_bnext.c* for sample code.

BUGS
----
Report bugs to support@mavimax.com

SEE ALSO
--------
*Bchg(3)* *Badd(3)* *CBadd(3)* *Bget(3)* *Boccur(3)*

COPYING
-------
(C) Mavimax, Ltd

