SYNOPSIS
--------

#include <ubf.h>


int Bvprint (char *'cstruct', char *'view');

int Bvfprint (char *'cstruct', char *'view', FILE *'outf');

int Bvfprintcb (char *'cstruct', char *'view', ndrx_plugin_tplogprintubf_hook_t 'p_writef', void *'dataptr1');


Link with '-lubf -lnstd -lm -lpthread'

DESCRIPTION
-----------
Group of functions used for printing the VIEW type structure. *Bvprint()* prints
the view to *stdout*. *Bvfprint()* prints the view to specified output file stream.
*Bvfprintcb()* prints the buffer to callback function.

The callback function shall be created according to *ndrx_plugin_tplogprintubf_hook_t*
signature which is:

--------------------------------------------------------------------------------
typedef int (*ndrx_plugin_tplogprintubf_hook_t)(char **buffer, long datalen, void *dataptr1, 
        int *do_write, FILE * outf, int fid);
--------------------------------------------------------------------------------

The callback receives 'buffer' parameter with ASCII chars to print. The 'datalen'
indicates the data length in the 'buffer', this includes a newline and EOS byte.
'dataptr1' is forwarded from the *Bvfprintcb()* call to callback. Parameters:
'do_write', 'outf' are not used. 'fid' is set field number starting from *0* which
is being printed.

Data format for printing to *stdout* or *FILE* stream is following:
"<FIELD><TAB><VALUE><NEW_LINE>". When printing to callback, additionally EOS (0x00)
byte is added for each of the lines printed in '\*buffer'.


When printing char, strings or carray data output is escaped with following rules,
if given ASCII chars is not *isprint()* or is *iscntrl()*, then data is escaped
as "\xx", where xx is hex number of byte, in lower case.


Example output:
--------------------------------------------------------------------------------
tshort4	-10
tlong1	33333333
tint2	54545
tint2	23232
tint3	-100
tint4	1010101
tint4	989898
tchar1	A
tchar2	A
tchar2	B
tchar2	C
tchar2	\0a
tchar2	\09
tfloat1	-0.11000
tfloat1	-0.22000
tfloat1	0.33000
tfloat1	0.44000
tfloat2	100000.10156
tfloat2	200000.20312
tfloat3	333333.12500
tdouble1	99999.111111
tdouble1	11111.999999
tdouble2	-999.123000
tstring0	HELLO Enduro/X
tcarray2	\01\02\03\04\05
--------------------------------------------------------------------------------

Following logic is applied for NULL view fields when printing:

...


RETURN VALUE
------------
On success, *Bgetr()* and *Bgetrv()* return zero; on error, -1 is returned, with *Berror* set to 
indicate the error.

ERRORS
------
Note that *Bstrerror()* returns generic error message plus custom message with 
debug info from last function call. Function my return errors from *Bfind(3)* and
corresponding mapped operation, e.g. *Bget(3)*, *Bfind(3)*, etc.

Following additional errors may be returned by this function:

*BBADFLD* Invalid sequence of field identifier, not encoded according the the rules.

*BEBADOP* For view operations (CBvgetr/CBvgetrv/Bvnullr/Bvnullrv), the leaf 
field identifier in sequence does not match the *view* type.

EXAMPLE
-------
See *ubftest/test_embubf.c* for sample code.

BUGS
----
Report bugs to support@mavimax.com

SEE ALSO
--------
*Bget(3)* *CBget(3)* *Bfind(3)* *CBfind(3)* *Bpres(3)* *CBvget(3)* *Bvnull(3)*

COPYING
-------
(C) Mavimax, Ltd

