TPJSONTOVIEW(3)
===============
:doctype: manpage


NAME
----
tpjsontoview - Convert JSON object to VIEW buffer


SYNOPSIS
--------
#include <atmi.h>

char * tpjsontoview(char *'view', char *'buffer')

For XATMI client link with '-latmiclt -latmi -lview -lnstd -lpthread -lrt -lm'

For XATMI server link with '-latmisrv|-latmisrvnomain|-latmisrvinteg -latmi -lview -lnstd -lpthread -lrt -lm'

DESCRIPTION
-----------
Function converts JSON formatted text in 'buffer' to VIEW buffer. JSON should
be formatted in two levels. In first level there is single field named as VIEW
name, and in second level JSON field names matches VIEW field name.
If multiple occurrances/array of values is present in JSON, 
then it is converted in VIEW field array elements.

For example following JSON:

--------------------------------------------------------------------------------
{  
   "T_SHORT_FLD":1765,
   "T_LONG_FLD":[  
      3333111,
      2
   ],
   "T_CHAR_FLD":"A",
   "T_FLOAT_FLD":1.330000,
   "T_DOUBLE_FLD":[  
      1111.220000,
      333,
      444
   ],
   "T_STRING_FLD":"HELLO WORLD",
   "T_CARRAY_FLD":"AAECA0hFTExPIEJJTkFSWQQFAA=="
}
--------------------------------------------------------------------------------

Can be loaded into following VIEW:

--------------------------------------------------------------------------------
T_SHORT_FLD     1765
T_LONG_FLD      3333111
T_LONG_FLD      2
T_CHAR_FLD      A
T_FLOAT_FLD     1.33000
T_DOUBLE_FLD    1111.220000
T_DOUBLE_FLD    333.000000
T_DOUBLE_FLD    444.000000
T_STRING_FLD    HELLO WORLD
T_CARRAY_FLD    \00\01\02\03HELLO BINARY\04\05\00
--------------------------------------------------------------------------------

Note that *BFLD_CARRAY* (binary data) fields should be present in base64 encoding
in JSON buffer. It is up to user to allocate VIEW buffer with enought size to fit
the converted message.

RETURN VALUE
------------
On success, *tpcall()* return zero; on error, -1 is returned, with *tperrno*
set to indicate the error.

ERRORS
------
Note that *tpstrerror()* returns generic error message plus custom message with 
debug info from last function call.

*TPEINVAL* Invalid JSON or invalid base64 encoding, 

*TPESYSTEM* VIEW sub-system error, JSON sub-system error.

*TPEOS* System failure occurred during serving. See logs i.e. user log, or 
debugs for more info. In case of insufficient memory this error will be 
generated too.

EXAMPLE
-------
See *atmitest/test024_json/atmiclt24.c* for sample code.

BUGS
----
Report bugs to support@mavimax.com 

SEE ALSO
--------
*ndrxdebug.conf(5)*, *tpviewtojson(3)* *tpjsontoview(3)* tpviewtojson(3)*

COPYING
-------
(C) Mavimax, Ltd

