#!/bin/bash
## 
##
## @file ndrx_home
##
## -----------------------------------------------------------------------------
## Enduro/X Middleware Platform for Distributed Transaction Processing
## Copyright (C) 2009-2016, ATR Baltic, Ltd. All Rights Reserved.
## Copyright (C) 2017-2018, Mavimax, Ltd. All Rights Reserved.
## This software is released under one of the following licenses:
## GPL or Mavimax's license for commercial use.
## -----------------------------------------------------------------------------
## GPL license:
## 
## This program is free software; you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free Software
## Foundation; either version 3 of the License, or (at your option) any later
## version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
## PARTICULAR PURPOSE. See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along with
## this program; if not, write to the Free Software Foundation, Inc., 59 Temple
## Place, Suite 330, Boston, MA 02111-1307 USA
##
## -----------------------------------------------------------------------------
## A commercial use license is available from Mavimax, Ltd
## contact@mavimax.com
## -----------------------------------------------------------------------------
##
echo "Loading ndrx_home..."
# Where app domain lives
export NDRX_APPHOME=/home/mvitolin/projects/endurox
# Where NDRX runtime lives
export NDRX_HOME=/home/mvitolin/projects/endurox/dist/bin
# Debug config too
export NDRX_DEBUG_CONF=/home/mvitolin/projects/endurox/sampleconfig/debug.conf
# NDRX config too.
export NDRX_CONFIG=/home/mvitolin/projects/endurox/sampleconfig/ndrxconfig.xml

# For PY testing...
export PATH=$PATH:/home/mvitolin/projects/endurox/py/tuxmodule-python2/test:/home/mvitolin/projects/endurox:/home/mvitolin/projects/endurox/dist/bin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mvitolin/projects/endurox/dist/lib
export export FLDTBLDIR=/home/mvitolin/projects/endurox/ubftest/ubftab

export LD_LIBRARY_PATH=/home/mvitolin/projects/endurox/dist/lib:/home/mvitolin/tmp/lib/instantclient_12_1
