EnduroX Internal Develper Guide
===============================
Madars Vitolins
v1.0, 2012-12:
	Initial draft
:doctype: book

EnduroX Development standard
----------------------------
EnduroX build system is CMake. Version used should be 2.8 and above. It uses
Flex and Bison for building UBF (FML) Expressions.

Intension is done with as 4x spaces. EnduroX is programmed in NetBeans c/c++
project. NetBeans supports CMake projects.

Project also uses 'libxml2' (provided by system), 'uthash' (already included in 'include' dir) 
and cgreen (integrated into Enduro/X) for unit testing.
Gsoap (also included in ThirdParity/web_services) is used for webservice access
layer generation.

WebService generator uses mono (v4) for c source generation.


Unit testing
------------

Bot UBF and ATMI sub-systems are unit tested. UBF tests are located under 
'ubftest' folder, which could be run by:

--------------------------------------------------------------------------------
$ ./ubfunit1 2>/dev/null
Running "main"...
Completed "main": 5749 passes, 0 failures, 0 exceptions.
--------------------------------------------------------------------------------

ATMI tests are located at 'atmitest' directory, can be run by:
--------------------------------------------------------------------------------
$ ./run.sh 
tail -n1 test.out
Completed "main": 18 passes, 0 failure, 0 exceptions.
--------------------------------------------------------------------------------


EnduroX libraries
-----------------

The framework is composed by following internal libraries and it's dependencies:
[dia, module_dependency.dia, module_dependency.png, x300]
-------------------------------
-------------------------------

Queuing mechanisms
------------------

Enduro/X originally was developed for GNU/Linux kernels where resource polling sub-system
i.e. epoll() can handle Posix queue handlers. This is linux non-standard feature which 
greatly supports system development. This allows to build one queue - multiple servers
architecture (even for ATMI server processes waiting on different queues). However, this
this feature limits platform to be working on Linux only.

[dia, epoll_message_dispatch_mode.dia, epoll_message_dispatch_mode.png, x300]
-------------------------------
-------------------------------

Starting from Enduro/X version 3, there is support for other Posix compatible Operating
Systems. Where possible Posix queues are used. If no Queueu support built in, for example
Apple OSX, then emulated posix queues are used. For these platforms, the caller processes
does choose the queue where to send the message in round-robin mode. For each service
shared memory contains list of server IDs providing the service. In round robin mode
the server id is selected, and caller sends the service to queue (e.g. 'dom1,svc,TESTSVC,102'
where '102' is server id.).

[dia, poll_message_dispatch_mode.dia, poll_message_dispatch_mode.png, x450]
-------------------------------
-------------------------------

For other unix support, mq_notify() call for each open queue is installed, by employing
SIGUSR2. Signal handling is done in seperate thread. The main ATMI server thread is doing
'poll()' in unnamed pipe. When event from mq_ sub-system is received, it writes the queue
descriptor id to unnamed pipe and that makes main thread to wake up for queue processing.
The 'poll()' for main thread supports Enduro/X extensions to add some other resource for
polling (e.g. socket fd.)

:numbered!:

[bibliography]
Additional documentation 
------------------------
This section lists additional related documents.

[bibliography]
.Internet resources
- [[[ATMI-API]]] http://docs.oracle.com/cd/E13203_01/tuxedo/tux71/html/pgint6.htm
- [[[FML-API]]] http://docs.oracle.com/cd/E13203_01/tuxedo/tux91/fml/index.htm

[glossary]
Glossary
--------
This section lists

[glossary]
ATMI::
  Application Transaction Monitor Interface

UBF::
  Unified Buffer Format it is similar API as Tuxedo's FML


////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
