Getting Started Tutorial
========================
Madars Vitolins
v1.0, 2015-11:
	Initial draft
:doctype: book

About the guide
---------------
Getting started tutorial covers Enduro/X installation from binary package,
environment setup, creating a sample Enduro/X server and creating sample client.
This include creating a neccessary configuration files. Finally the applicatioin is booted,
and client process calls the sample server process.

== Configuring Linux Kernel parameters

Kernel parameter configuration is needed for Enduro/X runtime. It includes changing
the security and Posix queue settings.

=== Security Configuration
---------------------------------------------------------------------
$ su - root
# cat << EOF >> /etc/security/limits.conf

# Do not limit message Q Count.
# Some Linux 3.x series kernels have a bug, that limits 1024 
# queues for one system user.
# In 2.6.x and 4.x this is fixed, to have 
# unlimited count of queues (memory limit).
# ealrier and later Linuxes have fixed this issue.
*               soft    msgqueue        -1
*               hard    msgqueue        -1

# Increase the number of open files 
*               soft    nofile  1024
*               hard    nofile  65536

EOF
---------------------------------------------------------------------

=== Message Queue Configuration
At the startup of the system needs to mount a Posix Queues folder, and needs to 
set a appropriate limits. To do this automatically at system startup, 
Linuxes which supports '/etc/rc.local', must add following lines before "exit 0":

---------------------------------------------------------------------
# Mount the /dev/mqueue
mkdir /dev/mqueue
mount -t mqueue none /dev/mqueue

# Max Messages in Queue
echo 10000 > /proc/sys/fs/mqueue/msg_max

# Max message size (Currently Enduro/X supports only 32K as max)
echo 32000 > /proc/sys/fs/mqueue/msgsize_max

# Max number of queues for user
echo 10000 > /proc/sys/fs/mqueue/queues_max
---------------------------------------------------------------------

== Installing binary package (RPM for Centos 6.x)
---------------------------------------------------------------------
# wget http://www.endurox.org/attachments/download/6/endurox-2.3.2-1.centos6.x86_64.rpm
# rpm -i endurox-2.3.2-1.centos6.x86_64.rpm
---------------------------------------------------------------------

== Configuring the application environment 
We will run our app "app1" from new user "user1". Application domain will be located in /opt/app1 folder. With follwing direcotry structure:
[options="compact"]
- /opt/app1/conf - will contain configuration files.
- /opt/app1/src/bankcl - Enduro/X sample client process source
- /opt/app1/src/banksv - Enduro/X sample server process sources.
- /opt/app1/bin - for executables.
- /opt/app1/ubftab - for tables for field defintions.
- /opt/app1/tmp - temp dir
- /opt/app1/log - for logging

Create the user & directories:
---------------------------------------------------------------------
# useradd -m user1
# mkdir -p /opt/app1/conf
# mkdir -p /opt/app1/src/bankcl
# mkdir -p /opt/app1/src/banksv
# mkdir -p /opt/app1/bin
# mkdir -p /opt/app1/ubftab
# mkdir -p /opt/app1/tmp
# mkdir -p /opt/app1/log
# chown -R user1 /opt/app1 
---------------------------------------------------------------------
Next we will configure environment files, file /opt/app1/conf/setndrx - this will contain neccessary configuration for Enduro/X.

Copy following text to /opt/app1/conf/setndrx
---------------------------------------------------------------------
#!/bin/bash
export NDRX_NODEID=1
# If 1 - then yes, if 0 - then not clusterised.
export NDRX_CLUSTERISED=0
# Load balance, 0 = process all locally, 100 = process all on remote servers
export NDRX_LDBAL=0
# tpcall() timeout:
export NDRX_TOUT=60
# where to write ulog
export NDRX_ULOG=/opt/app1/log
export NDRX_QPREFIX=/app1
export NDRX_SVCMAX=20000
export NDRX_SRVMAX=10000
export NDRX_QPATH=/dev/mqueue
export NDRX_SHMPATH=/dev/shm
# Milli seconds to wait for command
export NDRX_CMDWAIT=1
export NDRX_DPID=/opt/app1/tmp/ndrxd.pid
# Random key to indentify the processes beloning to this session (i.e. used in ps ef)
export NDRX_RNDK="0myWI5nu"
# System V Semaphores...
export NDRX_IPCKEY=44000
# Posix queue config (attribs..)
# Max number of messages that can be put in one queue
export NDRX_MSGMAX=1000
# Daemon Q size...
export NDRX_DQMAX=100
# Max message size (in bytes), max 64K
export NDRX_MSGSIZEMAX=10000
# Where app domain lives
export NDRX_APPHOME=/opt/app1
# Where NDRX runtime lives
export NDRX_HOME=/usr
# Debug config too
export NDRX_DEBUG_CONF=/opt/app1/conf/debug.conf
# NDRX config too.
export NDRX_CONFIG=/opt/app1/conf/ndrxconfig.xml
export PATH=$PATH:/opt/app1/bin
export export FLDTBLDIR=/opt/app1/ubftab
# Max fields for hashing UBF
export NDRX_UBFMAXFLDS=16000

# Log & levels (basic for scripting..)
export NDRX_DMNLOG=/opt/app1/log/ndrxd.log
export NDRX_DMNLEV=5

export NDRX_LOG=/opt/app1/log/xadmin.log
export NDRX_LEV=5

# Correct the path so that ndrx can find ndrxd
export PATH=$PATH:$NDRX_HOME/bin

# UBFTAB Exfields - Enduro/X specifc, bank.fd - our apps' UBF fields 
export FIELDTBLS=Exfields,bank.fd
---------------------------------------------------------------------

Basic application server configuration (/opt/app1/conf/ndrxconfig.xml)

---------------------------------------------------------------------
<?xml version="1.0" ?>
<endurox>
    <appconfig>
         <!-- ALL BELLOW ONES USES <sanity> periodical timer  -->
         <!-- Sanity check time, sec -->
         <sanity>5</sanity>
         <!--
             Seconds in which we should send service refresh to other node.
         -->
         <brrefresh>6</brrefresh>
         
         <!--  <sanity> timer, end -->
         
         <!-- ALL BELLOW ONES USES <respawn> periodical timer  -->
         <!-- Do dead process restart every X seconds 
         NOT USED ANYMORE, REPLACED WITH SANITY!
         <respawncheck>10</respawncheck>
         -->
         <!-- Do process reset after 1 sec -->
         <restart_min>1</restart_min>
         <!-- If restart fails, then boot after +5 sec of previous wait time -->
         <restart_step>1</restart_step>
         <!-- If still not started, then max boot time is a 30 sec. -->
         <restart_max>5</restart_max>
         <!--  <sanity> timer, end -->
         
         <!-- Time after attach when program will start do sanity & respawn checks,
              starts counting after configuration load -->
         <restart_to_check>20</restart_to_check>
         
         <!-- Setting for pq command, should ndrxd collect service 
              queue stats automatically
         If set to Y or y, then queue stats are on.
         Default is off.
         -->
         <gather_pq_stats>Y</gather_pq_stats>
         
	</appconfig>
    <defaults>
        <min>1</min>
        <max>2</max>
        <!-- Kill the process which have not started in <start_max> time -->
        <autokill>1</autokill>
        <!--
        <respawn>1<respawn>
        -->
        <!--
            <env></env> works here too!
        -->
         <!-- The maximum time while process can hang in 'starting' state i.e.
            have not completed initialization, sec
            X <= 0 = disabled 
        -->
         <start_max>2</start_max>
         <!--
            Ping server in every X seconds (step is <sanity>).
         -->
         <pingtime>1</pingtime>
         <!--
            Max time in seconds in which server must respond.
            The granularity is sanity time.
            X <= 0 = disabled 
         -->
         <ping_max>4</ping_max>
         <!--
            Max time to wait until process should exit on shutdown
            X <= 0 = disabled 
         -->
         <end_max>30</end_max>
         <!-- Interval, in seconds, by which signal sequence -2, -15, -9, -9.... will be sent
         to process until it have been terminated. -->
         <killtime>1</killtime>
         <!-- List of services (comma separated) for ndrxd to export services over bridges -->
    <!--     <exportsvcs>FOREX</exportsvcs> -->
	</defaults>
	<servers>
		<!-- This is binary we are about to build -->
		<server name="banksv">
			<srvid>1</srvid>
			<min>2</min>
			<max>2</max>
			<sysopt>-e /opt/app1/log/BANKSV -r</sysopt>
		</server>
	</servers>
</endurox>
---------------------------------------------------------------------


Setup debug config (/opt/app1/conf/debug.conf):

---------------------------------------------------------------------
* ndrx=5 ubf=0 lines=1 bufsz=1000 file=
xadmin file=${NDRX_APPHOME}/log/xadmin.log
ndrxd file=${NDRX_APPHOME}/log/ndrxd.log
eserver file=${NDRX_APPHOME}/log/BANKSV
eclient file=${NDRX_APPHOME}/log/BANKCL
---------------------------------------------------------------------

We will get the default Exfields version and will 
try to start the app server, should start, except `banksv' will not be found:

---------------------------------------------------------------------
$ cp /usr/share/endurox/ubftab/Exfields /opt/app1/ubftab
$ cd /opt/app1/conf
$ chmod +x setndrx
$ . setndrx
$ xadmin start -y

Enduro/X v2.3.2, build Nov 16 2015 08:22:23

Enduro/X Middleware Platform for Distributed Transaction Processing
Copyright (C) 2015, ATR Baltic, SIA. All Rights Reserved.

This software is released under one of the following licenses:
GPLv2 (or later) or ATR Baltic's license for commercial use.

EnduroX back-end (ndrxd) is not running!
ndrxd PID (from PID file): 1695
ndrxd idle instance started!
exec banksv -k 0myWI5nu -i 1 -e /opt/app1/log/BANKSV -r --  :
	process id=1696 ... No such file or directory.
exec banksv -k 0myWI5nu -i 2 -e /opt/app1/log/BANKSV -r --  :
	process id=1698 ... No such file or directory.
Startup finished. 0 processes started.
---------------------------------------------------------------------
This is ok, we have configured two copies of eserver Enduro/X servers, which we are not yet built,
thus we get the error.

If you run `xadmin' and get following error:

---------------------------------------------------------------------
$ xadmin
Failed to initialize!
---------------------------------------------------------------------

Then this typically means, that you do not have run /etc/rc.local (either by root or by reboot). More info is logged
to /opt/app1/log/xadmin.log

== Creating the server process
Firstly to create a "bank" server, we will have to define the fields in which we will transfer the data. We will need following fields:
[options="compact"]
- T_ACCNUM - Account number, type string
- T_ACCCUR - Account currency, type string
- T_AMTAVL - Available balance in account, type double
So we will create a service "BALANCE" to which we will T_ACCNUM and T_ACCCUR. The process will return balance in T_AMTAVL.

=== Defining the UBF fields
Requried fields will be define into /opt/app1/ubftab/bank.fd with follwing contents:

---------------------------------------------------------------------
$/* -----------------------------------------------------------------------------
$** Bank app field defintions for UBF buffer
$** -----------------------------------------------------------------------------
$*/

$#ifndef __BANK_H
$#define __BANK_H

*base 1000

#NAME		ID	TYPE	FLAG	COMMENT
#----		--	----	----	-------
# Service name for UD
T_ACCNUM	1	string	-	Account number
T_ACCCUR	2	string	-	Account currency
T_AMTAVL	3	double	-	Account balance

$#endif
---------------------------------------------------------------------

To generate C header fields for UBF buffer, run `mkfldhdr' command in /opt/app1/ubftab folder:

---------------------------------------------------------------------
$ mkfldhdr 
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0265:Output directory is [.]
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0277:Use environment variables
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0337:enter generate_files()
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0395:/opt/app1/ubftab/Exfields processed OK, output: ./Exfields.h
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0395:/opt/app1/ubftab/bank.fd processed OK, output: ./bank.fd.h
NDRX:5: 2038:000:20151116:033733008:fldhdr.c:0290:Finished with : SUCCESS
ls -l
total 16
-rw-r--r--. 1 user1 user1  459 Nov 16 03:36 bank.fd
-rw-rw-r--. 1 user1 user1  525 Nov 16 03:37 bank.fd.h
-rw-r--r--. 1 user1 user1 3704 Nov 16 03:18 Exfields
-rw-rw-r--. 1 user1 user1 3498 Nov 16 03:37 Exfields.h
---------------------------------------------------------------------


=== Server source code

=== Booting the server process

=== Testing the service with "ud" command

== Creating the client application

=== Client binary source code

=== Running the client process

== Conclusions

:numbered!:

[bibliography]
Additional documentation 
------------------------
This section lists additional related documents.

[bibliography]
.Internet resources
- [[[ATMI-API]]] http://docs.oracle.com/cd/E13203_01/tuxedo/tux71/html/pgint6.htm
- [[[FML-API]]] http://docs.oracle.com/cd/E13203_01/tuxedo/tux91/fml/index.htm
- [[[EX_OVERVIEW]]] ex_overview.pdf
- [[[MQ_OVERVIEW]]] 'man 7 mq_overview'
- [[[EX_ENV]]] 'man 5 ex_env' or 'ex_env.pdf'
- [[[NDRXCONFIG]]] 'man 5 ndrxconfig.xml'  or 'ndrxconfig.xml.pdf'
- [[[DEBUGCONF]]] 'man 5 ndrxdebug.conf'  or 'ndrxdebug.conf.pdf'
- [[[XADMIN]]] 'man 8 xadmin' or 'xadmin.pdf'

[glossary]
Glossary
--------
This section lists

[glossary]
ATMI::
  Application Transaction Monitor Interface

UBF::
  Unified Buffer Format it is similar API as Tuxedo's FML


////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
