Building Enduro/X On HP-UX Platform
===================================
Madars Vitolins
v1.0, 2017-04:
	Initial draft
:doctype: book

About manual
------------
This document describes Enduro/X building process on hp-ux 11i version 3. Tutorial
is prepared for Itaninum platform, but should be valid for PA-RISC too.

== Overview
This installation process will highlet the packages to be installed and will point o

== Installation process
Install the open source packages from:  http://hpux.connect.org.uk/. Following
packages are needed:

. git (e.g. http://hpux.connect.org.uk/hppd/hpux/Development/Tools/git-2.13.2)

. cmake (Needs to install from sources, bellow)

. flex (e.g. http://hpux.connect.org.uk/hppd/hpux/Gnu/flex-2.6.4/)

. bison  (e.g. http://hpux.connect.org.uk/hppd/hpux/Gnu/bison-3.0.4/)

. libxml2 (.e.g http://hpux.connect.org.uk/hppd/hpux/Gnome/libxml2-2.9.4/)

. wget - needed for package download

. gcc (if try GNU Compiler Chain .e.g. http://hpux.connect.org.uk/hppd/hpux/Gnu/gcc-4.2.3/,
http://hpux.connect.org.uk/hppd/hpux/Gnu/libgcc-4.2.3/) 

. aCC (if running with HP-UX native compiler)

. libexpat (or use /opt/gtk2.6/lib/libexpat.so and synmlink to /opt/gtk2.6/lib/libexpat.so /usr/lib/hpux32/libexpat.so )

. libidn
 

=== Installing aCC
Install the compiler from purchased copy or just take a trial version from HP-UX:
- https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=B9007AAEVAL

But seems that site is closed now.

=== Packages to be installed

Once way would be to install all the packages manually, but thanks to HP, you
can use depohelper script which will install all packages automatically.

Download the corresponding scripts from:

http://hpux.connect.org.uk/hppd/cgi-bin/search?term=depothelper

http://www.thegeekstuff.com/2010/10/hpux-depothelper/

If you have some issues with swinstall:


- https://community.hpe.com/t5/System-Administration/Swinstall-swlist-Could-not-contact-host/td-p/5075728


- https://community.hpe.com/t5/General/No-depot-software-at-location-var-spool-sw/td-p/4587988


Install depo helper first:

---------------------------------------------------------------------

# swinstall -s /root/depothelper-2.00-ia64-11.31.depot \*

---------------------------------------------------------------------

Then install packages needed:

If you get something like this, then probably internet is now working on your server (gateway
or DNS):

- https://community.hpe.com/t5/Patches/Package-installation-using-Depothelper/td-p/6136275


---------------------------------------------------------------------


# /usr/local/bin/depothelper git
==============================================================================================================================================
Package-version      Comment              Download        Install
==============================================================================================================================================
ia64-11.31           Package list         FAILED          Not installed       
==============================================================================================================================================
ERROR: Can't get list of ia64-11.31 packages from hpux.connect.org.uk - aborted

---------------------------------------------------------------------

We solved this by manually installing the packages.


...

=== Installing Cmake

The CMake is not available for HP depot, thus we will compile it from sources:


---------------------------------------------------------------------

# /usr/local/bin/wget --no-check-certificate https://cmake.org/files/v3.9/cmake-3.9.0-rc5.tar.gz
# gzip -d cmake-3.9.0-rc5.tar.gz
# tar -xf cmake-3.9.0-rc5.tar
# export PATH=$PATH:/usr/local/bin
# cd cmake-3.9.0-rc5
# ./configure
# make 
# make install

---------------------------------------------------------------------

if you get something like this:


-------------------------------------------------------------------------------


[ 26%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/arm.c.o
(Bundled) cc: warning 922: "-Aa" is unsupported in the bundled compiler, ignored.
(Bundled) cc: warning 922: "-Ae" is unsupported in the bundled compiler, ignored.
"/root/cmake-3.9.0-rc5/Utilities/cmliblzma/liblzma/simple/simple_private.h", line 64: error #2070: 
          incomplete type is not allowed
        uint8_t buffer[];

        
-------------------------------------------------------------------------------

Then you may try to fix the code in editor and change those empty arrays to declared with 1 element:

-------------------------------------------------------------------------------


        /// Temporary buffer
        uint8_t buffer[1];
};
"/root/cmake-3.9.0-rc5/Utilities/cmliblzma/liblzma/simple/simple_private.h" 75 lines, 225
5 characters


-------------------------------------------------------------------------------


=== Getting the Enduro/X source code

-------------------------------------------------------------------------------

# useradd -m user1
# su - user1

$ bash
$ chmod +w .profile
$ cat << EOF >> .profile

export SHLIB_PATH=$SHLIB_PATH:/usr/local/lib/hpux64:/opt/hpsmh/lib
PATH=$PATH:/usr/local/bin
EOF

$ chmod +x .profile
$ source .profile
$ cd /home/user1
$ GIT_SSL_NO_VERIFY=true git clone https://github.com/endurox-dev/endurox
$ cd endurox
$ git config http.sslVerify "false"

-------------------------------------------------------------------------------


=== Enduro/X basic Environment configuration for HOME directory
...

---------------------------------------------------------------------
$ cat << EOF > $HOME/ndrx_home
#!/bin/bash

# Where app domain lives
export NDRX_APPHOME=/home/user1/endurox
# Where NDRX runtime lives
export NDRX_HOME=/home/user1/endurox/dist/bin
# Debug config too
export NDRX_DEBUG_CONF=/home/user1/endurox/sampleconfig/debug.conf

# NDRX config too.
export NDRX_CONFIG=/home/user1/endurox/sampleconfig/ndrxconfig.xml

# Access for binaries
export PATH=$PATH:/$HOME/endurox/dist/bin

# LIBPATH for .so 
export LD_LIBRARY_PATH=:$HOME/endurox/dist/lib64

# UBF/FML field tables
export FLDTBLDIR=$HOME/endurox/ubftest/ubftab

EOF

$ chmod +x $HOME/ndrx_home
---------------------------------------------------------------------

=== Building the code with aCC
...

---------------------------------------------------------------------

=== Building the code with GCC
...

== Unit Testing

Enduro/X basically consists of two parts:
. XATMI runtime;
. UBF/FML buffer processing. 
Each of these two sub-systems have own units tests.

=== UBF/FML Unit testing

---------------------------------------------------------------------
$ cd /home/user1/endurox/sampleconfig
$ source setndrx
$ cd /home/user1/endurox/ubftest
$ ./ubfunit1 2>/dev/null
... TODO: ...
---------------------------------------------------------------------

=== XATMI Unit testing
...

---------------------------------------------------------------------
$ cd /home/user1/endurox/atmitest
$ nohup ./run.sh &
$ tail -f /home/user1/endurox/atmitest/test.out
...
************ FINISHED TEST: [test028_tmq/run.sh] with 0 ************
Completed "atmi_test_all": 28 passes, 0 failures, 0 exceptions.
Completed "main": 28 passes, 0 failures, 0 exceptions.
---------------------------------------------------------------------

== Trouble shooting

=== Rebuilding with other compiler

...

=== Thread local storage issues
...


== Conclusions
...

:numbered!:

[bibliography]
Additional documentation 
------------------------
This section lists additional related documents.

[bibliography]
.Resources
- [[[BINARY_INSTALL]]] See Enduro/X 'binary_install' manual.


////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
