Building Enduro/X On HP-UX Platform
===================================
Madars Vitolins
v1.0, 2017-04:
	Initial draft
:doctype: book

About manual
------------
...

== Overview
...

== Installation process
...

. git
. cmake
. flex
. bison
. libxml2
. gcc (if try GNU Compiler Chain)
. aCC (if running with HP-UX native compiler)
 

=== Installing aCC
Install the compiler from purchased copy or just take a trial version from HP-UX:
- https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=B9007AAEVAL

=== Packages to be installed
...

=== Getting the source code
...



=== Enduro/X basic Environment configuration for HOME directory
...

---------------------------------------------------------------------
$ cat << EOF > $HOME/ndrx_home
#!/bin/bash

# Where app domain lives
export NDRX_APPHOME=/home/user1/endurox
# Where NDRX runtime lives
export NDRX_HOME=/home/user1/endurox/dist/bin
# Debug config too
export NDRX_DEBUG_CONF=/home/user1/endurox/sampleconfig/debug.conf

# NDRX config too.
export NDRX_CONFIG=/home/user1/endurox/sampleconfig/ndrxconfig.xml

# Access for binaries
export PATH=$PATH:/$HOME/endurox/dist/bin

# LIBPATH for .so 
export LD_LIBRARY_PATH=:$HOME/endurox/dist/lib64

# UBF/FML field tables
export FLDTBLDIR=$HOME/endurox/ubftest/ubftab

EOF

$ chmod +x $HOME/ndrx_home
---------------------------------------------------------------------

=== Building the code with aCC
...

---------------------------------------------------------------------

=== Building the code with GCC
...

== Unit Testing

Enduro/X basically consists of two parts:
. XATMI runtime;
. UBF/FML buffer processing. 
Each of these two sub-systems have own units tests.

=== UBF/FML Unit testing

---------------------------------------------------------------------
$ cd /home/user1/endurox/sampleconfig
$ source setndrx
$ cd /home/user1/endurox/ubftest
$ ./ubfunit1 2>/dev/null
... TODO: ...
---------------------------------------------------------------------

=== XATMI Unit testing
...

---------------------------------------------------------------------
$ cd /home/user1/endurox/atmitest
$ nohup ./run.sh &
$ tail -f /home/user1/endurox/atmitest/test.out
...
************ FINISHED TEST: [test028_tmq/run.sh] with 0 ************
Completed "atmi_test_all": 28 passes, 0 failures, 0 exceptions.
Completed "main": 28 passes, 0 failures, 0 exceptions.
---------------------------------------------------------------------

== Trouble shooting

=== Rebuilding with other compiler

...

=== Thread local storage issues
...


== Conclusions
...

:numbered!:

[bibliography]
Additional documentation 
------------------------
This section lists additional related documents.

[bibliography]
.Resources
- [[[BINARY_INSTALL]]] See Enduro/X 'binary_install' manual.


////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
