Migrating from Oracle Tuxedo to Enduro/X
========================================
:doctype: book

== About the guide

This document describes different aspects which needs to be accounted for
when performing migration from Oracle Tuxedo to Enduro/X middleware.
The document describes common elements which Enduro/X covers from Tuxedo
functionality, what functionality differs and what elements in Enduro/X
are missing and what alternatives are available to replace missing bits.

Lastly document describes standard approach for performing configuration
migration for Tuxedo UBB Config to Enduro/X based configuration

== Enduro/X and Tuxedo common bits

Both systems are build on X/Open *XATMI* and *XA* standards. Each of the systems
implement extensions over theses APIs. For example Tuxedo have *FML* key-value
structure format handling API. Enduro/X counterpart for this functionality is
*UBF* buffers which even provide emulation for *FML* via *fml.h* and *fml32.h*
headers shipped with Enduro/X.

Enduro/X tends to implement most majority of the C APIs which are typically used in
Tuxedo application. To verify your application compatibility with Enduro/X, 
perform manual scan over your code base and check each Tuxedo API in Enduro/X
documentation.

== Enduro/X and Tuxedo differences

=== UBB Configuration vs Enduro/X ini/xml format

*Tuxedo* use UBB configuration file, which is kind of extended ini file. This
describes majority of information used for Tuxedo application instance.

Other hand *Enduro/X* uses two separate files for the configuration. One is
XML configuration file (*ndrxconfig.xml* typically) which describes the XATMI
server and client processes, services and DDR info. The other file is standard 
*ini* file (typically *app.ini*) which include per binary configuration.

Typically Enduro/X application are configure with third environment file
which loads the env variables in the shell session. File name typically
starts with *set*.

=== Configuration groups

At Core of the *Tuxedo* application, principle of service grouping is used.
The grouping splits the binaries/servers in some logical groups. These
groups provides XA configuration per binary, also these groups internally
affect how XATMI IPC messages (such as *tpcall(3)*) land on the particular
server process instances.

...


=== Clustering

In Enduro/X applications each instance works as "master" node, forming
a peer to peer cluster. This means that each cluster node needs to be started
separately in opposite to Tuxedo, where cluster application is started from
master node, and secondary nodes are started by the master.

Enduro/X cluster works in similar fashion as Tuxedo Gateway, except that
*tpforward(3)* and all other APIs work in the same mode as Tuxedo's multi-machine
configuration (i.e. MODEL=MP).

== Tuxedo connectivity and bindings

- Enduro/X does not have *WebLogic Tuxedo Connector* or *Jolt* libraries
for Java. But Enduro/X provides Web Services interface module *endurox-connect*,
particularly *restincl(8)* from which XATMI services can be exposed as JSONS 
web services. With this Enduro/X services may be called from any language which supports web
services. Web services API provides capability for managing global transactions.

- Enduro/X counterpart to the Tuxedo *SALT* is endurox-connect module. The
*restincl(8)* serves the inbound web services traffic and *restousv(8)* services
the outbound traffic. The message formats between *SALT* and *endurox-connect*
are different. Enduro/X counter part tends to use *JSON* message formats. However
*restincl* is extensible and provides general purpose module for incoming
web traffic handling from XATMI perspective (this includes any kind of web traffic
handling, file upload, custom message formats, etc.).

- *endurox-java* package serves as direct counterpart of the *Oracle Tuxedo Java*. Some
of the APIs are different, but majority conforms to the *TJATMI*. Enduro/X implementation
is based on JNI binding code. Each java instance is started as separate binary.

== Migrating source code
...

== Migrating configuration
...

////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
