#Compiled VIEW file Enduro/X 5.4.1 LINUX 64 bit, compiler: GNU
#Time stamp: Oct 15 2018 20:44:34
#It is possible to use this file as source of the view and recompile it
#that will basically update the offsets and sizes of target platform
#@__platform=LINUX;@__arch=x86_64;@__wsize=64


VIEW MYVIEW56
#type  cname                fbname          count flag    size  null                 compiled_data
short  tshort1              -               1     -       -     -                    offset=0;fldsize=2;
long   tlong1               -               1     -       -     -                    offset=8;fldsize=8;
char   tchar1               -               1     -       -     -                    offset=16;fldsize=1;
float  tfloat1              -               1     -       -     -                    offset=20;fldsize=4;
double tdouble1             -               1     -       -     -                    offset=24;fldsize=8;
string tstring1             -               1     -       15    -                    offset=32;fldsize=15;
carray tcarray1             -               1     -       10    -                    offset=47;fldsize=10;
#@__ssize=64;@__cksum=3844477102
END

