#!/usr/bin/perl
## 
## @(#) Builds Enduro/X client process
##
## @file buildclient
## 
## -----------------------------------------------------------------------------
## Enduro/X Middleware Platform for Distributed Transaction Processing
## Copyright (C) 2015, Mavimax, Ltd. All Rights Reserved.
## This software is released under one of the following licenses:
## GPL or Mavimax's license for commercial use.
## -----------------------------------------------------------------------------
## GPL license:
## 
## This program is free software; you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free Software
## Foundation; either version 2 of the License, or (at your option) any later
## version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
## PARTICULAR PURPOSE. See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along with
## this program; if not, write to the Free Software Foundation, Inc., 59 Temple
## Place, Suite 330, Boston, MA 02111-1307 USA
##
## -----------------------------------------------------------------------------
## A commercial use license is available from Mavimax, Ltd
## contact@mavimax.com
## -----------------------------------------------------------------------------
##

use Getopt::Std;
use Cwd;


my %options=();
getopts("o:f:a:", \%options);

my $CFLAGS = $ENV{'CFLAGS'};

# Support #104, mvitolin 23/03/2017 - give chance to change compiler
my $CC = "cc";
if ($ENV{'CC'})
{
	$CC=$ENV{'CC'};
}

my $CFLAGS="";

if ($ENV{'CFLAGS'})
{
	$CFLAGS=$ENV{'CFLAGS'};
}

my $LIBPATH = $ENV{'LIBPATH'};
my $BUILD_LIB_PATH="";

# Print out the options we have
print "-o $options{o}\n" if defined $options{o};
print "-f $options{f}\n" if defined $options{f};

# Extract the CFLAGS
@CFLAGS_ARR = split (/ |\t+/,$CFLAGS);

foreach my $item (@CFLAGS_ARR) {
	if ($item =~ m/-L.*/ || $item =~ m/-l.*/)
	{
		print "$item\n";
		$BUILD_LIB_PATH="$BUILD_LIB_PATH $item";
	}
}

# Extract LIBPATH
@LIBPATH_ARR = split (":",$LIBPATH);
foreach my $item (@LIBPATH_ARR) {
	$BUILD_LIB_PATH="$BUILD_LIB_PATH -L$item";
}

# Set RT LIB
my $dyn_libs = "-lrt -ldl -lpthread";
my $wd = getcwd;

print "OS Version: $^O wd: $wd\n";

if ($^O eq "freebsd" )
{
	$dyn_libs = "-lrt -lpthread";
}
elsif ($^O eq "darwin")
{
	$dyn_libs = "-ldl -lpthread";
}

$command="$CC $CFLAGS -o $options{o} $options{f}  -latmiclt -latmi -lubf -lnstd $dyn_libs -lm -lc -lpthread $BUILD_LIB_PATH $options{a}";

print "$command\n";
`$command`
