TMQUEUE(8)
==========
:doctype: manpage


NAME
----
tmqueue - Transactional Message Queue server.


SYNOPSIS
--------
*tmqueue* ['OPTIONS']


DESCRIPTION
-----------
This is special ATMI server which is used for transactional persistent queue operations.
*tmqueue* is backend server used by *tpenqueue* and *tpdequeue()* calls. Queue server
works in pair with *tmsrv(8)* instance, where both *tmqueue* and *tmsrv* are configured in
XA environment which uses 'NDRX_XA_RMLIB=libndrxxaqdisk.so' and 
*NDRX_XA_DRIVERLIB=libndrxxaqdisks.so* (static registration driver) or 
*NDRX_XA_DRIVERLIB=libndrxxaqdiskd.so* (dynamic registration driver). 
Each message basically is file in file-system which synchronously is kept in 
queue server's memory. The files in file system are staged between *active*, 
*prepared* and *committed* states. During the *active* and *prepared* stages 
messages are made after the XA transaction ID (with sequence number after dash).
when message is committed, it is moved to *committed* directory, where filename 
contains the actual message id. This infrastructure also is used for issuing XA 
commands which does the remove or update of the message i.e. at the commit moment 
command files are used to update/remove committed message.

The folder where to store the processing qspace files are *NDRX_XA_OPEN_STR* 
and *NDRX_XA_CLOSE_STR* environment variables. Is is possible to combine 
multiple instances of *tmqueue* for the same qspace, but it is recommended to 
keep qspace folders different. However, it shall also work with same folder.

The queue server internally uses thread pools for handling the work. Multiple 
thread pools are used to avoid the deadlocking where internal processing might 
do the XA driver calls which in the end sends notifications to the same server back.

Three thread-pools are used:

1) First one is for accepting the ATMI *tpcall(3)* requests. 

2) Second thread pool is used by forward services (which basically are senders
for automatic queues). 

3) Third thread pool is used by notifications received from transaction manager 
(TM). TM notifies the queue server for completion (commit) of the message. So 
that *tmqueue* can unlock the message in memory. 


Every instance of *tmqueue* will advertise following list of services:

1. @TMQ-<Cluster Node ID>-<Server ID>

2. @QSP<Queue space>

For example for Queue Space 'MYSPACE', Cluster Node ID '6', Enduro/X Server ID '100'
services will look like:

1.  @TMQ-6-100

2.  @QSPMYSPACE

The automatic forwarder pool, ever configured time, will scan the automatic 
queues for non-locked messages. Once such message is found, the message is 
submitted for worker thread. The worker thread will do the synchronous call to 
target server ('srvnm' from 'q.conf'), wait for answer and either update tries 
counter or remove the message if succeed. If message is submitted with 'TPQREPLYQ' 
then on success, the response message from invoked service is submitted to 
reply queue. If message destination service fails for number of attempts,
then message is forwarded to 'TPQFAILUREQ', in this case original 'TPQCTL' is preserved.

During the startup, *tmqueue* will read messages from the disk. All messages are read.
Messages from *active* and *prepared* directories are read and status for them
is set to locked (no dequeue possible). Messages from *committed* folder are 
read without the lock flag. However, other command files (delete, update) from 
*active' and *prepared* directories are analyzed and they will lock the messages too, 
as they are indicating that transaction are progress.

In case if *tmqueue* was shutdown with incomplete transactions, the *tmsrv(8)*
will be responsible for finalizing the transactions when *tmqueue* will be started.

The *tpenqueue(3)* and *tpdequeue(3)* can be invoked either as part of the global
 transaction or not. If global transaction is not used, then *tmqueue* will 
open the transactions internally.

For more usage of the persistent queues, configuration, command line and codding samples, 
see *atmitests/test028_tmq* folder.


OPTIONS
-------
*-m* 'QUEUE_SPACE'::
The name of the queue space.

[*-q* 'QUEUE_CONFIG']::
This either full or relative path to the queue definition file (see 'q.conf(5)' 
for more info on syntax. When changes are done in this file, it is possible to 
reload the configuration during the runtime, with 'xadmin mqrc' command. Note 
that queues are not removed, but changed or added. If flag is not set,
then data is searched in *[@queue]* ini section. And uses *<cctag>* for
sub-section search, if multiple Q-spaces are defined. Firstly it attempts 
to load form this flag specified configuration file, afterwards attempt is 
made to load from CConfig if available.

[*-s* 'SCAN_TIME']::
This time in seconds used by main forwarder thread to scan for any automatic 
messages to be submitted for processing.

[*-p* 'SERVICE_THREAD_POOL_SIZE']::
This is thread pool size of used for 'tpenqueue()', 'tpdequeue()' serving. 
Also this thread pool is utilized by 'xadmin mqX' commands. Default is '10'.

[*-u* 'NOTIFY_THREAD_POOL_SIZE']::
This is number of threads which are processing callbacks from XA driver 
(for operation completion notifications).

[*-f* 'FORWARD_THREAD_POOL_SIZE']::
This is number of worker threads for forwarder. Default value is '10'.

[*-t* 'XA_TRANSACTION_TIMEOUT']::
Maximum number of seconds to wait for XA transaction to be completed. This used 
internally when global transactions are not used. Default is '30'.

[*-h* 'HOUSEKEEP_TIMEOUT']::
Number of seconds used to determine should the corrupted file existing in 'active'
folder shall be unlinked. Flag is needed for purpose that concurrent processes
might be witting the file and it is not yet completed. Thus longer the delay will
ensure that no race condition would caused for concurrent processes. If file
is older than given seconds, during the *tmqueue* startup, such damaged file
will be unlinked. Default value is *3600* (1 hour).

LIMITATIONS
-----------
When commit is performed for several enqueued messages within global transaction,
each message is unblocked (made available in queue space for dequeue or automatic
forward) separately, message by message. So this means that during the commit
execution, even thought commit is not completed yet, part of the messages will
appear as committed.

Flag *NOJOIN* is not supported for XA libndrxxaqdisks and libndrxxaqdiskd drivers.

ASSUMPTIONS
-----------
To ensure transactionality of the message files, following assumptions are used:

- File system file rename operation is atomic.

- Disk sector writes are assumed to be atomic. Thought even if for some reason 
they are not atomic, then Enduro/X will be able to guarantee
message consistency in case if disk sector is written from left to right or from
right to left.

- In case if disk sector writes are not atomic (normally they should be), then
requirement for disk sub-system is to not to corrupt the file contents. Either
to have old data bytes or new data bytes written. Disk must not write any random
data in case of power loss or any other accident.

DISK FAILURE HANDLING
---------------------
In case if new message is being added and message file cannot be added  
(disk full or other error) in *active* folder, *tperror* is set to 
*TPEDIAGNOSTIC* and *QMEOS* error is set in *TPQCTL.diagnostic*. If empty file
was created it is removed.

In case if manual dequeue is performed, and *tmqueue* cannot create command file
(used by tmsrv for completion of two phase commit), dequeue operation will fail
with *TPEDIAGNOSTIC*/*QMEOS*. Any empty command files are removed.

In case if queue is automatic, forward process takes the message from the memory 
and sends to the process, when result is known the command file is issued for 
two phase commit completion. In case of disk failure, command file is not written,
empty file is removed. The transaction is aborted. In this particular case,
messages in *tmqueue* messages are not unlocked. Thus if there was disk issues,
the *tmqueue* shall be restarted, to proceed with enqueued message processing.

In case if message/command files in the *active* folder are corrupted for some
reason, the *tmqueue* process at the startup will detect such files and if 
their age according to creation date/time in FS is older than *-h* setting,
then files are removed. Such files in *committed* or *prepared* folders are not
removed, error message is printed in the log and *tmqueue* will proceed with
loading of the next message.


EXIT STATUS
-----------
*0*::
Success

*1*::
Failure

BUGS
----
Report bugs to support@mavimax.com

SEE ALSO
--------
*xadmin(8)* *q.conf(5)* *ex_env(5)* *tmsrv(8)*

COPYING
-------
(C) Mavimax, Ltd

