XADMIN(8)
========
:doctype: manpage


NAME
----
xadmin - EnduroX Administration command line utility


SYNOPSIS
--------
*xadmin* ['COMMAND'] ['OPTIONS']


DESCRIPTION
-----------
'xadmin' is command line interface to EnduroX. It is administration utility.
Which is servers as communication interface between EnduroX ATMI local daemon
and administrator. 'xadmin' can receive commands as parameter to 'xadmin'. It
can read command from pipe (stdin). And it can work in interactive mode. In this
case 'xadmin' is started with no parameters.

'xadmin' is responsible to start idle instance of 'ndrxd'. After that 'xadmin'
sends commands to 'ndrxd' and prints the response from daemon to the stdout in
human readable form. Commands are sent and response from 'ndrxd' are received
via POSIX Queues.


COMMANDS
-------
*quit*::
	Quit from command line utility
*q*::
	Alias for quit
*echo*::
	Echo text back to terminal
*idle*::
	Enter daemon process in idle state (if not started)
*help*::
	Print help (this output)
*stat*::
	Prints general status information
*ldcf*::
	Load configuration
*start* [-y] [-s <server>] [-i <srvid>]::
	Start application domain. If config not loaded, it loads
	configuration automatically. '-y' means do not ask for confirmation. '-s' means
	ATMI servers binary name to be started, instead of whole application domain.
	'-i' means start specific server instance.
*psc*::
	Print services
*stop* [-y] [-c]|[-s <server>] [-i <srvid>]::
	Stop application domain. '-y' means do not ask for confirmation. '-s' means
	ATMI servers binary name to be stopped, instead of whole application domain.
	'-i' means stop specific server instance. '-c' flag will shutdown 'ndrxd' daemon,
	otherwise daemon keeps running.
*sreload* [-y] [-s <server>] [-i <srvid>]::
	Reload application domain - restart server instance by instance.
	Configuration be loaded prior.
	'-y' means do not ask for confirmation. '-s' means ATMI servers binary name 
	to be reloaded, instead of whole application domain.
	'-i' means restart specific server instance.
*sr*::
	Alias for 'sreload'
*psc*::
	
*down* [-y]::
	Force appserver shuttdown & resurce cleanup. RUN ONLY IF YOU KNOW WHAT YOU ARE DOING!
	Basically this kills all ATMI servers and EnduroX daemon. This does NOT remove client
	processes.
*cat*::
	Attached console to ndrxd user session in progress
*reload*::
	Load new configuration
*testcfg*::
	Test new configuration
*unadv* -i server_id -s service_name::
	Un-advertise service. '-i' is server id, '-s' is service name to be
	unadvertised.
*readv* -i server_id -s service_name::
	Re-advertise service. Might be usable if service Q was unlinked.
	'-i'  is server id, '-s' is service name to be re-advertised.
*restart* [-y] [-s <server>] [-i <srvid>]::
	Restart app or service (invokes start & stop with same args!). '-y'
	makes to not to ask for confirmation. '-s' is server/binary name. '-i' is server ID.
*r*::
	Alias for 'restart'
*-v*::
	Print version info
*ver*::
	Alias for '-v'
*ppm*::
	Print process model
*psvc*::
	Shared mem, print services
*psrv*::
	Shared mem, print servers
*cabort* [-y]::
	Abort shutdown or startup operation in progress. '-y' do not ask for confirmation.
*sreload* [-y] [-s <server>] [-i <srvid>]::
	Restart servers instance by instance
*pq*::
	Print Queue stats from ndrxd.
*pqa* [-a]::
	Print all queues including client and admin Q. '-a' includes other prefix queues.
*pt*::
	Print global transactions in progress.
*printtrans*::
	Alias for 'pt'.
*abort* -t <transaction_manager_reference> -x <XID> [-g <resource_manager_id>] [-y]::
	Abort transaction. '-g' does abort single resource manager's transaction.
	'-y' is for auto confirmation.
*aborttrans*::
	Alias for 'abort'.
*commit* -t <transaction_manager_reference> -x <XID> [-y]::
	Commit transaction. '-y' is for auto confirmation.
*committrans*::
	Alias for 'commit'.
*pe*::
	Print Environment variables of 'ndrxd' process.
*printenv*::
	Alias for 'pe'.
*set* ENV_NAME=ENV VALUE::
	Set environment value. The value of env variable is parsed as command line arguments.
        Prior sending to 'ndrxd' they are contact with spaces in between.
*unset* ENV_NAME::
        Unset environment variable
*pc*::
	Print client processes. This sends command to Client Process Monitor server ('cpmsrv').
*bc* -t <process tag> [-s <sub section>]::
	Boot client process. This sends command to Client Process Monitor server ('cpmsrv').
	Processes are registered in 'ndrxconfig.xml' '<clients>' section.
*sc* -t <process tag> [-s <sub section>]::
	Stop client process. This sends command to Client Process Monitor server ('cpmsrv').

*mqlc*::
	List queue configuration. This broadcasts the requests of config listing to all 
	'tmqueue' servers. If flags column contains 'D' flag, then it means that queue
	was dynamically defined and QDEF string contains values from default queue.
*mqlq*::
	List actual queues allocated on system. Similarly as for 'mqlc' this requests
	the information from all 'tmqueue' servers. '#LOCK' column contains the number
	of active non committed messages in Q. '#SUCC' and '#FAIL' column contains number
	of processed messages for automatic queues (messages are sent to destination services
	automatically by 'tmqueue' server.
*mqrc*::
	This command requests all queue servers to reload the configuration file.
*mqlm* -s <QSpace> -q <QName>::
	List messages in queue. '-s' is queue space name (set by 'tmqueue' '-m' paramemter).
	The output lists the message ID in modified base64 version ('/' changed to '_').
*mqdm* -n <Cluster node id> -i <Server ID> -m <Message ID>::
	Dump/peek message to stdout. The values from '-n' (node id), '-i' (srvid), '-m'(message id)
	can be taken from 'mqlm' command. This command prints to stdout, the 'TQCTL' structure in form
	of UBF buffer and the message it self. If message is UBF, then UBF dump is made, otherwise
	hexdump of message is printed.
	
EXIT STATUS
-----------
*0*::
Success

*1*::
Failure

BUGS
----
Report bugs to madars.vitolins@gmail.com

SEE ALSO
--------
*ndrxd(8)*

AUTHOR
------
EnduroX is created by Madars Vitolins.


COPYING
-------
(C) Madars Vitolins

