/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
#ifndef _CONFIG_H_
#define _CONFIG_H_

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

#define HAVE_GETOPT_H 1

#define HAVE_PROGNAME 1

/* #undef EX_USE_EPOLL */

#define EX_OS_LINUX 1

/* #undef EX_OS_AIX */

/* #undef EX_OS_HPUX */

/* #undef EX_OS_SUNOS */

/* #undef EX_OS_FREEBSD */

/* #undef EX_OS_CYGWIN */

/* Use emulated message queue: */
#define EX_USE_EMQ 1

/* Defined if pscript is off */
/* #undef NDRX_DISABLEPSCRIPT */


/* Use FS based registry for mq */
#define USE_FS_REGISTRY ON

/* The size of `long', as computed by sizeof. */
#define SIZEOF_INT 4

#define NDRX_VERSION   "Enduro/X 2.5.1"
#define NDRX_BUILD_OS_NAME "LINUX"

/* PThread mode for Solaris */
#define _POSIX_PTHREAD_SEMANTICS

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)

#if defined(atmi_EXPORTS) || defined(atmiclt_EXPORTS) || defined(atmisrv_EXPORTS) || defined(atmisrvinteg_EXPORTS) || defined(atmisrvnomain_EXPORTS) || defined(exnet_EXPORTS) || defined(ndrxxaorad_EXPORTS) || defined(ndrxxaoras_EXPORTS) || defined(ndrxxaqdisk_EXPORTS) || defined(ndrxxaqdiskd_EXPORTS) || defined(ndrxxaqdisks_EXPORTS) || defined(netproto_EXPORTS) || defined(nstd_EXPORTS) || defined(ubf_EXPORTS)
        /* We are building this library */
#      define NDRX_API __declspec(dllexport)
#else
        /* We are using this library */
#       define NDRX_API __declspec(dllimport)
#endif

#else

#       define NDRX_API

#endif

#endif
