* ndrx=3 ubf=1 lines=1 bufsz=1000 file= threaded=l
xadmin ndrx=3 file=${TESTDIR}/xadmin-dom1.log
ndrxd ndrx=3 file=${TESTDIR}/ndrxd-dom1.log
tmqueue ndrx=4 threaded=l file=${TESTDIR}/tmqueue-dom2.log
tmsrv file= ndrx=4
